// Apex Legends roster — Season 29 "Overclocked" (May 2026).
// Tier ratings reflect competitive ranked + pubs viability; community-aggregated.

export type LegendClass =
  | "Assault"
  | "Skirmisher"
  | "Recon"
  | "Support"
  | "Controller";

export type Legend = {
  id: string;
  name: string;
  realName: string;
  class: LegendClass;
  tier: "S" | "A" | "B" | "C" | "D";
  passive: { name: string; text: string };
  tactical: { name: string; text: string; cooldown: number };
  ultimate: { name: string; text: string; cooldown: number };
  perks: { name: string; tier: 2 | 3; text: string }[];
  strengths: string[];
  weaknesses: string[];
  counters: string[]; // legend ids that counter this legend
  pairsWith: string[]; // legend ids that pair well
  pickRate: number; // % ranked Plat+
  winRate: number; // % ranked Plat+
  pro: string; // one-line pro tip
};

export const LEGENDS: Legend[] = [
  {
    id: "wraith",
    name: "Wraith",
    realName: "Renee Blasey",
    class: "Skirmisher",
    tier: "A",
    passive: {
      name: "Voices from the Void",
      text: "A voice warns when an enemy is aiming at you or you are about to be ambushed.",
    },
    tactical: {
      name: "Into the Void",
      text: "Reposition quickly through the safety of void space, avoiding all damage.",
      cooldown: 25,
    },
    ultimate: {
      name: "Dimensional Rift",
      text: "Link two locations with portals for 60 seconds. Teammates can pass through.",
      cooldown: 180,
    },
    perks: [
      { name: "Faster Phase", tier: 2, text: "+15% phase move speed." },
      { name: "Long Portal", tier: 3, text: "+25% portal range." },
    ],
    strengths: ["Smallest hitbox", "Repositioning", "Team rotations"],
    weaknesses: ["Low utility outside fights", "Phase animation telegraph"],
    counters: ["seer", "bloodhound", "caustic"],
    pairsWith: ["bangalore", "gibraltar", "newcastle"],
    pickRate: 9.4,
    winRate: 6.1,
    pro: "Phase the moment you hear voices — don't second-guess the passive.",
  },
  {
    id: "octane",
    name: "Octane",
    realName: "Octavio Silva",
    class: "Skirmisher",
    tier: "A",
    passive: {
      name: "Swift Mend",
      text: "Restore 1 health per second when not taking damage.",
    },
    tactical: {
      name: "Stim",
      text: "Take 12 damage to move 30% faster for 6 seconds. Cannot heal during.",
      cooldown: 1,
    },
    ultimate: {
      name: "Launch Pad",
      text: "Deployable jump pad. Jump again mid-air for a high-arc double jump.",
      cooldown: 60,
    },
    perks: [
      { name: "Free Stim", tier: 2, text: "Stim costs 0 HP." },
      { name: "Mad Hops", tier: 3, text: "Double jump from launch pad goes higher and farther." },
    ],
    strengths: ["Rotational speed", "Self-sustain", "Hot drops"],
    weaknesses: ["Damages himself", "No scan, no scout"],
    counters: ["caustic", "wattson", "rampart"],
    pairsWith: ["pathfinder", "valkyrie", "horizon"],
    pickRate: 11.8,
    winRate: 5.4,
    pro: "Stim before peeking — extra strafe speed beats most aim.",
  },
  {
    id: "bloodhound",
    name: "Bloodhound",
    realName: "Bloth Hundr",
    class: "Recon",
    tier: "S",
    passive: {
      name: "Tracker",
      text: "See tracks left by enemies, with timestamps and counts.",
    },
    tactical: {
      name: "Eye of the Allfather",
      text: "Reveal hidden enemies, traps, and clues in front of you for 2 seconds.",
      cooldown: 25,
    },
    ultimate: {
      name: "Beast of the Hunt",
      text: "Heightened senses + 30% speed. Lower scan cooldown. 30s base, extended on knocks.",
      cooldown: 180,
    },
    perks: [
      { name: "Long Scan", tier: 2, text: "+15% scan range." },
      { name: "Trail Marker", tier: 3, text: "Reveal teammates that follow your trail." },
    ],
    strengths: ["Information", "Aggressive scout", "Counters movement"],
    weaknesses: ["No defensive utility", "Scan tells enemies your direction too"],
    counters: ["mirage", "loba"],
    pairsWith: ["gibraltar", "fuse", "ash"],
    pickRate: 10.2,
    winRate: 6.8,
    pro: "Scan AFTER first damage — pre-scanning wastes the cooldown.",
  },
  {
    id: "gibraltar",
    name: "Gibraltar",
    realName: "Makoa Gibraltar",
    class: "Support",
    tier: "S",
    passive: {
      name: "Gun Shield",
      text: "Aiming down sights deploys a 75 HP gun shield that blocks incoming fire.",
    },
    tactical: {
      name: "Dome of Protection",
      text: "20-second dome that blocks all damage. Allies inside heal +25% faster.",
      cooldown: 30,
    },
    ultimate: {
      name: "Defensive Bombardment",
      text: "Call a concentrated mortar strike on a 6m radius for 6 seconds.",
      cooldown: 270,
    },
    perks: [
      { name: "Fast Dome", tier: 2, text: "Throw dome 30% faster." },
      { name: "Double Bombardment", tier: 3, text: "Mortar lasts +3s." },
    ],
    strengths: ["Cover on demand", "Revives in dome", "End-zone hold"],
    weaknesses: ["Big hitbox", "Slow"],
    counters: ["caustic", "horizon", "wattson"],
    pairsWith: ["wraith", "bloodhound", "lifeline"],
    pickRate: 7.6,
    winRate: 7.4,
    pro: "Dome on the knock, not before — pre-domes waste the cooldown.",
  },
  {
    id: "lifeline",
    name: "Lifeline",
    realName: "Ajay Che",
    class: "Support",
    tier: "A",
    passive: {
      name: "Combat Medic",
      text: "DOC drone revives knocked teammates while you fight. Heal items 25% faster.",
    },
    tactical: {
      name: "D.O.C. Heal Drone",
      text: "Healing drone heals 8 HP/s in 4m radius for 8 seconds.",
      cooldown: 45,
    },
    ultimate: {
      name: "Care Package",
      text: "Drop a high-tier care package with 3 attachments scaled to team's gear.",
      cooldown: 240,
    },
    perks: [
      { name: "DOC Shield", tier: 2, text: "DOC blocks 1 line-of-sight while reviving." },
      { name: "Fast Revives", tier: 3, text: "DOC revives 30% faster." },
    ],
    strengths: ["Free revives", "Aggressive heals", "Solo carry potential"],
    weaknesses: ["DOC drone is visible", "Care package drop predicted"],
    counters: ["caustic", "ash"],
    pairsWith: ["octane", "wraith", "ballistic"],
    pickRate: 8.9,
    winRate: 6.2,
    pro: "Start a revive then immediately swap to your gun — DOC finishes alone.",
  },
  {
    id: "pathfinder",
    name: "Pathfinder",
    realName: "MRVN",
    class: "Skirmisher",
    tier: "B",
    passive: {
      name: "Insider Knowledge",
      text: "Scan survey beacons to reveal the next ring location. Ult cooldown reduced 10s per beacon.",
    },
    tactical: {
      name: "Grappling Hook",
      text: "30m grapple to walls, ceilings, or zip down to ground.",
      cooldown: 20,
    },
    ultimate: {
      name: "Zipline Gun",
      text: "Place a 150m two-way zipline for the whole squad.",
      cooldown: 90,
    },
    perks: [
      { name: "Long Grapple", tier: 2, text: "+10m grapple range." },
      { name: "Two Ziplines", tier: 3, text: "Carry two ziplines at once." },
    ],
    strengths: ["Mobility", "Ring info", "Repositions"],
    weaknesses: ["Big hitbox for skirmisher", "Grapple cooldown long"],
    counters: ["caustic", "wattson"],
    pairsWith: ["octane", "valkyrie", "wraith"],
    pickRate: 6.8,
    winRate: 5.1,
    pro: "Crouch-grapple under cover — it ends the grapple silently and faster.",
  },
  {
    id: "horizon",
    name: "Horizon",
    realName: "Mary Somers",
    class: "Skirmisher",
    tier: "S",
    passive: {
      name: "Spacewalk",
      text: "Increased air control and reduced fall impact.",
    },
    tactical: {
      name: "Gravity Lift",
      text: "Vertical lift that gently launches teammates and enemies upward.",
      cooldown: 21,
    },
    ultimate: {
      name: "Black Hole",
      text: "N.E.W.T. deploys a micro black hole that pulls enemies in for 12s.",
      cooldown: 180,
    },
    perks: [
      { name: "Long Lift", tier: 2, text: "Lift lasts +3s." },
      { name: "Black Hole Stun", tier: 3, text: "Black hole pulse stuns enemies." },
    ],
    strengths: ["Vertical control", "Team setups", "Wide-area ult"],
    weaknesses: ["Lift telegraphs position", "No scan"],
    counters: ["caustic", "wattson", "rampart"],
    pairsWith: ["fuse", "bangalore", "gibraltar"],
    pickRate: 9.1,
    winRate: 6.9,
    pro: "Lift the doorway you're holding — enemies pushing get launched & shot from above.",
  },
  {
    id: "valkyrie",
    name: "Valkyrie",
    realName: "Kairi Imahara",
    class: "Skirmisher",
    tier: "S",
    passive: {
      name: "VTOL Jets",
      text: "Hold jump to fly with jetpacks. Scan beacons reveal ring like Pathfinder.",
    },
    tactical: {
      name: "Missile Swarm",
      text: "Fire a swarm of mini rockets that disorient and damage.",
      cooldown: 35,
    },
    ultimate: {
      name: "Skyward Dive",
      text: "Launch with teammates into the sky and skydive to reposition.",
      cooldown: 180,
    },
    perks: [
      { name: "Hover Fuel", tier: 2, text: "+25% jetpack fuel." },
      { name: "Long Dive", tier: 3, text: "+30% Skyward Dive range." },
    ],
    strengths: ["Best rotations", "Recon info", "Disengage anywhere"],
    weaknesses: ["Loud jetpack", "Skydive predictable"],
    counters: ["caustic", "wattson"],
    pairsWith: ["bloodhound", "gibraltar", "newcastle"],
    pickRate: 8.5,
    winRate: 7.2,
    pro: "Ult to higher ground before ring close — most teams forget you can fly to it.",
  },
  {
    id: "caustic",
    name: "Caustic",
    realName: "Alexander Nox",
    class: "Controller",
    tier: "A",
    passive: {
      name: "Nox Vision",
      text: "See enemies through your gas. Take less gas damage.",
    },
    tactical: {
      name: "Nox Gas Trap",
      text: "Throwable gas canister that triggers on enemy proximity.",
      cooldown: 25,
    },
    ultimate: {
      name: "Nox Gas Grenade",
      text: "Lobbable gas grenade with massive AoE.",
      cooldown: 150,
    },
    perks: [
      { name: "Bigger Cloud", tier: 2, text: "+20% gas radius." },
      { name: "Sticky Gas", tier: 3, text: "Gas slows enemies by 30%." },
    ],
    strengths: ["Building hold", "Endgame zones", "Anti-push"],
    weaknesses: ["Slow", "Passive in pubs"],
    counters: ["fuse", "ash", "bangalore"],
    pairsWith: ["wattson", "rampart", "gibraltar"],
    pickRate: 6.2,
    winRate: 6.4,
    pro: "Stack traps near revives — enemies third-partying knocks always trigger them.",
  },
  {
    id: "bangalore",
    name: "Bangalore",
    realName: "Anita Williams",
    class: "Assault",
    tier: "A",
    passive: {
      name: "Double Time",
      text: "Sprint 30% faster for 2s when taking fire.",
    },
    tactical: {
      name: "Smoke Launcher",
      text: "Lob 2 smokes that create a 4m smoke cloud.",
      cooldown: 33,
    },
    ultimate: {
      name: "Rolling Thunder",
      text: "Mortar carpet that detonates in waves over a wide area.",
      cooldown: 180,
    },
    perks: [
      { name: "Triple Smoke", tier: 2, text: "Carry a 3rd smoke charge." },
      { name: "Long Thunder", tier: 3, text: "+30% Rolling Thunder area." },
    ],
    strengths: ["Disengage", "Cover on demand", "Movement passive"],
    weaknesses: ["Smoke seen through scan & digital threat"],
    counters: ["bloodhound", "seer"],
    pairsWith: ["bloodhound", "valkyrie", "newcastle"],
    pickRate: 9.7,
    winRate: 6.3,
    pro: "Smoke between you and the shooter — passive triggers and they lose vision.",
  },
  {
    id: "wattson",
    name: "Wattson",
    realName: "Natalie Paquette",
    class: "Controller",
    tier: "A",
    passive: {
      name: "Spark of Genius",
      text: "Ult accelerant fully charges your ult. Slowly regenerate shields.",
    },
    tactical: {
      name: "Perimeter Security",
      text: "Place electrified fence nodes that damage and slow enemies.",
      cooldown: 0,
    },
    ultimate: {
      name: "Interception Pylon",
      text: "Pylon shoots down grenades & heals shields in radius.",
      cooldown: 180,
    },
    perks: [
      { name: "Charged Fences", tier: 2, text: "Fences slow enemies by 30%." },
      { name: "Long Pylon", tier: 3, text: "Pylon lasts +30s." },
    ],
    strengths: ["End-game holds", "Grenade denial", "Shield regen"],
    weaknesses: ["No mobility", "Fences seen through walls"],
    counters: ["ash", "fuse", "ballistic"],
    pairsWith: ["caustic", "rampart", "gibraltar"],
    pickRate: 5.4,
    winRate: 6.7,
    pro: "Pylon goes BEHIND your fences, not in front — protect the pylon from grenades.",
  },
  {
    id: "fuse",
    name: "Fuse",
    realName: "Walter Fitzroy",
    class: "Assault",
    tier: "A",
    passive: {
      name: "Grenadier",
      text: "Carry an extra grenade per stack. Throw grenades farther, faster, more accurately.",
    },
    tactical: {
      name: "Knuckle Cluster",
      text: "Cluster bomb that detonates on impact and again over time.",
      cooldown: 25,
    },
    ultimate: {
      name: "The Motherlode",
      text: "Ring of fire that blocks LoS and damages enemies inside.",
      cooldown: 120,
    },
    perks: [
      { name: "Extra Cluster", tier: 2, text: "Carry 2 knuckle clusters." },
      { name: "Big Ring", tier: 3, text: "+25% Motherlode radius." },
    ],
    strengths: ["Anti-camp", "Building clear", "Pressure tool"],
    weaknesses: ["No mobility", "Tactical telegraphs"],
    counters: ["wattson", "caustic"],
    pairsWith: ["bloodhound", "ash", "horizon"],
    pickRate: 7.3,
    winRate: 6.1,
    pro: "Cluster + arc star combo melts shields — throw cluster first, arc into the slow.",
  },
  {
    id: "mirage",
    name: "Mirage",
    realName: "Elliott Witt",
    class: "Support",
    tier: "B",
    passive: {
      name: "Now You See Me...",
      text: "Cloak when reviving teammates or using respawn beacons.",
    },
    tactical: {
      name: "Psyche Out",
      text: "Send a controllable decoy. Press tactical again to detonate confusion pulse.",
      cooldown: 15,
    },
    ultimate: {
      name: "Life of the Party",
      text: "Cloak briefly and deploy a team of decoys that mimic your movement.",
      cooldown: 60,
    },
    perks: [
      { name: "Decoy HP", tier: 2, text: "Decoy survives 2 hits." },
      { name: "Long Cloak", tier: 3, text: "+2s ult cloak." },
    ],
    strengths: ["Sneak revives", "Confusion", "Solo carry"],
    weaknesses: ["Loud decoys", "Bloodhound, Seer, Digital threat"],
    counters: ["bloodhound", "seer"],
    pairsWith: ["lifeline", "gibraltar"],
    pickRate: 4.2,
    winRate: 5.6,
    pro: "Mirror your own crouch with the decoy — even pros track the wrong one.",
  },
  {
    id: "loba",
    name: "Loba",
    realName: "Loba Andrade",
    class: "Support",
    tier: "B",
    passive: {
      name: "Eye for Quality",
      text: "See nearby Epic and Legendary loot through walls.",
    },
    tactical: {
      name: "Burglar's Best Friend",
      text: "Teleport up to 32m by throwing your jump drive bracelet.",
      cooldown: 25,
    },
    ultimate: {
      name: "Black Market Boutique",
      text: "Spawn a portable shop. Each squadmate takes 2 items, you get extras.",
      cooldown: 90,
    },
    perks: [
      { name: "Long Tele", tier: 2, text: "+8m bracelet range." },
      { name: "Resupply", tier: 3, text: "Black market refills team's heals and ammo." },
    ],
    strengths: ["Loot economy", "Reposition", "Late-game ammo"],
    weaknesses: ["Loud bracelet", "Tactical animation slow"],
    counters: ["bloodhound", "caustic"],
    pairsWith: ["gibraltar", "lifeline", "wattson"],
    pickRate: 5.1,
    winRate: 5.9,
    pro: "Open black market mid-fight — the heals are FREE during the animation.",
  },
  {
    id: "ash",
    name: "Ash",
    realName: "Dr. Ashleigh Reid",
    class: "Assault",
    tier: "A",
    passive: {
      name: "Marked for Death",
      text: "See death boxes on the map; scan a box to see attackers' direction.",
    },
    tactical: {
      name: "Arc Snare",
      text: "Throw a tether that snares & damages the first enemy that crosses.",
      cooldown: 20,
    },
    ultimate: {
      name: "Phase Breach",
      text: "Open a one-way phase tunnel up to 60m. Teammates can follow.",
      cooldown: 90,
    },
    perks: [
      { name: "Triple Snare", tier: 2, text: "Carry 3 snares." },
      { name: "Long Breach", tier: 3, text: "+20m tunnel range." },
    ],
    strengths: ["Aggression", "Anti-revive", "Closes distance"],
    weaknesses: ["Linear ult", "Predictable third-party tool"],
    counters: ["wattson", "caustic"],
    pairsWith: ["bloodhound", "horizon", "fuse"],
    pickRate: 9.8,
    winRate: 6.6,
    pro: "Phase Breach lands you AT the box — instakill the rezzer mid-animation.",
  },
  {
    id: "seer",
    name: "Seer",
    realName: "Obi Edolasim",
    class: "Recon",
    tier: "B",
    passive: {
      name: "Heart Seeker",
      text: "ADS to see heartbeats of enemies within 75m.",
    },
    tactical: {
      name: "Focus of Attention",
      text: "Send a wave that reveals & interrupts enemy heals/revives.",
      cooldown: 30,
    },
    ultimate: {
      name: "Exhibit",
      text: "Reveal sprinting enemies and projectiles in a 75m sphere.",
      cooldown: 90,
    },
    perks: [
      { name: "Long Focus", tier: 2, text: "+15m tactical range." },
      { name: "Reveal Walkers", tier: 3, text: "Ult reveals walking enemies too." },
    ],
    strengths: ["Anti-heal", "Wide-area scan", "Stops revives"],
    weaknesses: ["Telegraphed tactical", "Less nerfed but still squishy"],
    counters: ["mirage", "ash"],
    pairsWith: ["bloodhound", "fuse", "gibraltar"],
    pickRate: 5.6,
    winRate: 5.5,
    pro: "Tactical interrupts revives — save it for the second knock.",
  },
  {
    id: "newcastle",
    name: "Newcastle",
    realName: "Jackson Williams",
    class: "Support",
    tier: "A",
    passive: {
      name: "Retrieve the Wounded",
      text: "Drag knocked teammates while reviving. Revive shield protects you.",
    },
    tactical: {
      name: "Mobile Shield",
      text: "Throwable shield drone that follows the direction you face.",
      cooldown: 25,
    },
    ultimate: {
      name: "Castle Wall",
      text: "Leap to an ally or area to slam down a fortified wall.",
      cooldown: 90,
    },
    perks: [
      { name: "Bigger Shield", tier: 2, text: "+25% mobile shield HP." },
      { name: "Long Castle", tier: 3, text: "+15m wall range." },
    ],
    strengths: ["Safe revives", "Cover on demand", "Team aggression"],
    weaknesses: ["Big hitbox", "Walls breakable"],
    counters: ["fuse", "ash"],
    pairsWith: ["valkyrie", "wraith", "bloodhound"],
    pickRate: 7.1,
    winRate: 7.0,
    pro: "Throw the mobile shield WHILE running — it follows you and blocks fire mid-rotate.",
  },
  {
    id: "ballistic",
    name: "Ballistic",
    realName: "August Brinkman",
    class: "Assault",
    tier: "B",
    passive: {
      name: "Sling",
      text: "Carry a 3rd weapon in your sling that ignores attachments.",
    },
    tactical: {
      name: "Whistler",
      text: "Slow-tracking projectile that overheats enemy weapons.",
      cooldown: 25,
    },
    ultimate: {
      name: "Tempest",
      text: "Boost yourself and teammates: faster reload, infinite ammo, and a slung weapon gold-tier.",
      cooldown: 120,
    },
    perks: [
      { name: "Two Whistlers", tier: 2, text: "Carry 2 whistlers." },
      { name: "Long Tempest", tier: 3, text: "+15s tempest duration." },
    ],
    strengths: ["3-weapon flex", "Team buff ult", "Mid-range disrupt"],
    weaknesses: ["Tactical projectile is slow", "Passive sling weak vs hi-tier"],
    counters: ["wraith", "octane"],
    pairsWith: ["lifeline", "horizon", "fuse"],
    pickRate: 5.0,
    winRate: 5.4,
    pro: "Tempest before pushing — gold mag + faster reload wins every trade.",
  },
  {
    id: "conduit",
    name: "Conduit",
    realName: "Rowenna Connelly",
    class: "Support",
    tier: "S",
    passive: {
      name: "Savior's Speed",
      text: "Sprint faster toward distant teammates.",
    },
    tactical: {
      name: "Radiant Transfer",
      text: "Throw shield batteries at allies for temporary shields that linger.",
      cooldown: 15,
    },
    ultimate: {
      name: "Energy Barricade",
      text: "Wall of jammers that damages enemies and amps allies' shields.",
      cooldown: 120,
    },
    perks: [
      { name: "Triple Battery", tier: 2, text: "Carry 3 tactical batteries." },
      { name: "Big Barricade", tier: 3, text: "+25% jammer barricade size." },
    ],
    strengths: ["Active shield support", "Engaging power", "Shield denial"],
    weaknesses: ["No personal mobility", "Tactical can miss"],
    counters: ["fuse", "ash"],
    pairsWith: ["bloodhound", "ash", "horizon"],
    pickRate: 9.2,
    winRate: 7.3,
    pro: "Pre-throw a tactical at the teammate pushing — they hit the fight already overshielded.",
  },
  {
    id: "vantage",
    name: "Vantage",
    realName: "Xiomara Contreras",
    class: "Recon",
    tier: "A",
    passive: {
      name: "Spotter's Lens",
      text: "ADS without a scope to range-find enemies and see squad info.",
    },
    tactical: {
      name: "Echo Relocation",
      text: "Reposition by jumping toward Echo, your flying bat companion.",
      cooldown: 15,
    },
    ultimate: {
      name: "Sniper's Mark",
      text: "Custom long-range rifle. Marked enemies take +50% damage from squad.",
      cooldown: 60,
    },
    perks: [
      { name: "Echo Boost", tier: 2, text: "+20% Echo jump distance." },
      { name: "Mark Stack", tier: 3, text: "Marks stack +25% damage per shot." },
    ],
    strengths: ["Long range", "Mobility", "Information"],
    weaknesses: ["Echo loud", "Sniper at close range awful"],
    counters: ["mirage", "wraith"],
    pairsWith: ["bloodhound", "newcastle", "horizon"],
    pickRate: 6.5,
    winRate: 6.4,
    pro: "Mark, swap to your primary, then squad-burst — Sniper's Mark stays applied.",
  },
  {
    id: "rampart",
    name: "Rampart",
    realName: "Ramya Parekh",
    class: "Controller",
    tier: "B",
    passive: {
      name: "Modded Loader",
      text: "Larger mags and faster reload on LMGs and the minigun.",
    },
    tactical: {
      name: "Amped Cover",
      text: "Deployable wall with shield top that amplifies outgoing damage.",
      cooldown: 25,
    },
    ultimate: {
      name: "Sheila",
      text: "Mountable minigun. Pick it up to carry. Reload-locked when moving.",
      cooldown: 60,
    },
    perks: [
      { name: "Triple Wall", tier: 2, text: "Carry 3 amped walls." },
      { name: "Sheila Heals", tier: 3, text: "+15 HP/s while mounted." },
    ],
    strengths: ["Hold a building", "Amped LMG damage", "End-game"],
    weaknesses: ["Walls break", "Sheila is loud and slow to set up"],
    counters: ["fuse", "valkyrie"],
    pairsWith: ["caustic", "wattson"],
    pickRate: 3.1,
    winRate: 5.2,
    pro: "Amped wall covers your reload — peek-shoot-reload behind it indefinitely.",
  },
  {
    id: "crypto",
    name: "Crypto",
    realName: "Park Tae Joon",
    class: "Recon",
    tier: "B",
    passive: {
      name: "Neurolink",
      text: "Drone scans show enemies to your whole squad up to 30m.",
    },
    tactical: {
      name: "Surveillance Drone",
      text: "Deploy a drone you can pilot. Scans beacons & enemies.",
      cooldown: 40,
    },
    ultimate: {
      name: "Drone EMP",
      text: "EMP from drone deals 50 shield damage, slows enemies, and destroys traps.",
      cooldown: 90,
    },
    perks: [
      { name: "Long Drone", tier: 2, text: "+30% drone range." },
      { name: "Sky Drone", tier: 3, text: "EMP also reveals enemies after detonation." },
    ],
    strengths: ["Intel", "Counter-camp", "Trap clearing"],
    weaknesses: ["Pilot is vulnerable", "Drone destroyed by 1 shot to body"],
    counters: ["bangalore", "fuse"],
    pairsWith: ["caustic", "wattson", "gibraltar"],
    pickRate: 3.6,
    winRate: 5.7,
    pro: "Throw drone into the next building before entering — saves you from a third-party.",
  },
  {
    id: "revenant",
    name: "Revenant",
    realName: "Kaleb Cross",
    class: "Skirmisher",
    tier: "A",
    passive: {
      name: "Stalker",
      text: "Climb higher and crouch-walk faster than other legends.",
    },
    tactical: {
      name: "Shadow Pounce",
      text: "Charge up and leap forward up to 35m.",
      cooldown: 25,
    },
    ultimate: {
      name: "Forged Shadows",
      text: "Gain 75 shadow shields that regenerate from knocks.",
      cooldown: 180,
    },
    perks: [
      { name: "Charged Leap", tier: 2, text: "+10m pounce range." },
      { name: "Tough Shadows", tier: 3, text: "+25 shadow shield HP." },
    ],
    strengths: ["Vertical assassin", "Shield ult", "Aggressive 1-clip"],
    weaknesses: ["No team utility", "Pounce telegraphs"],
    counters: ["caustic", "wattson"],
    pairsWith: ["bloodhound", "horizon", "conduit"],
    pickRate: 8.7,
    winRate: 6.5,
    pro: "Pounce off-angles — most teams check doors, not the rafters above.",
  },
  {
    id: "catalyst",
    name: "Catalyst",
    realName: "Tressa Smith",
    class: "Controller",
    tier: "A",
    passive: {
      name: "Barricade",
      text: "Reinforce doors so they take longer to break.",
    },
    tactical: {
      name: "Piercing Spikes",
      text: "Ferrofluid spikes that slow & damage enemies. Triggered by proximity.",
      cooldown: 25,
    },
    ultimate: {
      name: "Dark Veil",
      text: "Wall of ferrofluid that blocks vision and slows enemies on contact.",
      cooldown: 90,
    },
    perks: [
      { name: "Wide Spikes", tier: 2, text: "+20% spike area." },
      { name: "Long Veil", tier: 3, text: "+5s Dark Veil duration." },
    ],
    strengths: ["Vision denial", "End-game holds", "Door defense"],
    weaknesses: ["No mobility", "Veil shows from inside"],
    counters: ["fuse", "valkyrie"],
    pairsWith: ["caustic", "wattson", "rampart"],
    pickRate: 6.4,
    winRate: 6.8,
    pro: "Veil INTO the open zone — they can't shoot you while crossing.",
  },
  {
    id: "alter",
    name: "Alter",
    realName: "Alestra Hightower",
    class: "Skirmisher",
    tier: "B",
    passive: {
      name: "Gift from the Rift",
      text: "Loot deathboxes from a distance through small portals.",
    },
    tactical: {
      name: "Void Passage",
      text: "Create a portal through a wall or floor up to 25m.",
      cooldown: 25,
    },
    ultimate: {
      name: "Void Nexus",
      text: "Place a beacon teammates can teleport to within 90s.",
      cooldown: 75,
    },
    perks: [
      { name: "Long Passage", tier: 2, text: "+10m portal range." },
      { name: "Nexus Speed", tier: 3, text: "Allies teleport 30% faster." },
    ],
    strengths: ["Repositions", "Anti-camp", "Loot economy"],
    weaknesses: ["Passage shows blue glow", "Predictable rotations"],
    counters: ["bloodhound", "seer"],
    pairsWith: ["bangalore", "wraith", "conduit"],
    pickRate: 5.9,
    winRate: 5.3,
    pro: "Place the Nexus BEFORE pushing — free retreat if the fight turns.",
  },
  {
    id: "maggie",
    name: "Mad Maggie",
    realName: "Margaret Kōhere",
    class: "Assault",
    tier: "B",
    passive: {
      name: "Warlord's Ire",
      text: "Move faster with shotguns. See last enemies who damaged you through walls.",
    },
    tactical: {
      name: "Riot Drill",
      text: "Drill that pierces walls and damages enemies on the other side.",
      cooldown: 25,
    },
    ultimate: {
      name: "Wrecking Ball",
      text: "Ball that drops speed pads on detonation and stuns enemies.",
      cooldown: 90,
    },
    perks: [
      { name: "Two Drills", tier: 2, text: "Carry 2 riot drills." },
      { name: "Big Ball", tier: 3, text: "+25% wrecking ball stun radius." },
    ],
    strengths: ["Wall pressure", "Shotgun synergy", "Aggressive push"],
    weaknesses: ["No information", "Ball ult easy to dodge"],
    counters: ["wattson", "caustic"],
    pairsWith: ["fuse", "octane", "bangalore"],
    pickRate: 4.8,
    winRate: 5.6,
    pro: "Drill the door AND the wall — they don't know which side you're peeking.",
  },
  {
    id: "axle",
    name: "Axle",
    realName: "Axel Voss",
    class: "Skirmisher",
    tier: "A",
    passive: {
      name: "Slipstream",
      text: "Slide 20% faster and 25% farther. Slide preserved off short ledges.",
    },
    tactical: {
      name: "Kinetic Pulse",
      text: "Forward burst that knocks back enemies and breaks doors.",
      cooldown: 20,
    },
    ultimate: {
      name: "Velocity Field",
      text: "Drop a pad that grants squad-wide sprint and slide speed boost.",
      cooldown: 120,
    },
    perks: [
      { name: "Long Pulse", tier: 2, text: "+5m pulse range." },
      { name: "Boosted Field", tier: 3, text: "+15% velocity field speed bonus." },
    ],
    strengths: ["Slide-jam movement", "Squad push speed", "Door pressure"],
    weaknesses: ["No scan", "Tactical short range"],
    counters: ["caustic", "wattson", "rampart"],
    pairsWith: ["octane", "conduit", "horizon"],
    pickRate: 12.4,
    winRate: 6.8,
    pro: "Slide-cancel into Kinetic Pulse — uninterrupted forward momentum, enemies launched.",
  },
];

export const LEGEND_CLASSES: LegendClass[] = [
  "Assault",
  "Skirmisher",
  "Recon",
  "Support",
  "Controller",
];

// Class passives — Apex's class system grants these to every legend in class.
export const CLASS_PASSIVES: Record<LegendClass, { perk: string; bonus: string }> = {
  Assault: {
    perk: "Smart Loot",
    bonus: "Extra inventory slot. Sees weapon attachments in red supply bins.",
  },
  Skirmisher: {
    perk: "Low Profile",
    bonus: "Sees contents of care packages from afar.",
  },
  Recon: {
    perk: "Eye in the Sky",
    bonus: "Scans survey beacons to reveal ring locations.",
  },
  Support: {
    perk: "Med-Up",
    bonus: "Crafts banners. Heals 25% faster. Stacks heals deeper.",
  },
  Controller: {
    perk: "Zone Tac",
    bonus: "Scans ring console for next 2 rings.",
  },
};

export function findLegend(id: string) {
  return LEGENDS.find((l) => l.id === id);
}
