// Apex Legends weapons — Season 29 "Overclocked" meta.
// DPS = damage * RPM / 60. TTK = ms to drop a fully-shielded enemy (200HP).

export type WeaponClass =
  | "Assault Rifle"
  | "SMG"
  | "LMG"
  | "Sniper"
  | "Marksman"
  | "Shotgun"
  | "Pistol";

export type Ammo = "Light" | "Heavy" | "Energy" | "Shotgun" | "Sniper" | "Arrow" | "Light/Heavy";

export type Weapon = {
  id: string;
  name: string;
  class: WeaponClass;
  ammo: Ammo;
  tier: "S" | "A" | "B" | "C" | "D";
  damageBody: number;
  damageHead: number;
  rpm: number;
  magBase: number;
  magPurple: number;
  reloadSec: number;
  recoil: "low" | "medium" | "high";
  rangeOptimal: "close" | "close-mid" | "mid" | "mid-long" | "long";
  notes: string;
  pro: string; // pro tip
  isCarePackage?: boolean;
  isElite?: boolean;
  isHopUp?: string; // hop up requirement note
};

const ttk = (dmgBody: number, rpm: number) =>
  Math.round((200 / dmgBody) * (60_000 / rpm));

export const WEAPONS: Weapon[] = [
  {
    id: "r301",
    name: "R-301 Carbine",
    class: "Assault Rifle",
    ammo: "Light",
    tier: "S",
    damageBody: 14,
    damageHead: 28,
    rpm: 810,
    magBase: 18,
    magPurple: 28,
    reloadSec: 2.4,
    recoil: "low",
    rangeOptimal: "mid",
    notes: "The benchmark AR. Lowest recoil, best feel in the game.",
    pro: "Tap-strafe + R-301 beats most close fights — easier to control than the Flatline.",
  },
  {
    id: "flatline",
    name: "VK-47 Flatline",
    class: "Assault Rifle",
    ammo: "Heavy",
    tier: "A",
    damageBody: 19,
    damageHead: 38,
    rpm: 600,
    magBase: 20,
    magPurple: 30,
    reloadSec: 2.4,
    recoil: "high",
    rangeOptimal: "close-mid",
    notes: "Hits like a truck but the recoil pattern fights you.",
    pro: "Burst 4-5 rounds, reset, repeat — full auto past 30m is wasted bullets.",
  },
  {
    id: "havoc",
    name: "HAVOC Rifle",
    class: "Assault Rifle",
    ammo: "Energy",
    tier: "A",
    damageBody: 18,
    damageHead: 36,
    rpm: 672,
    magBase: 25,
    magPurple: 32,
    reloadSec: 3.2,
    recoil: "medium",
    rangeOptimal: "mid",
    notes: "Charge-up before firing, but rewards with rail-laser accuracy.",
    pro: "Turbocharger hop-up removes the wind-up — must-have attachment.",
    isHopUp: "Turbocharger",
  },
  {
    id: "nemesis",
    name: "Nemesis Burst AR",
    class: "Assault Rifle",
    ammo: "Energy",
    tier: "A",
    damageBody: 17,
    damageHead: 34,
    rpm: 760,
    magBase: 20,
    magPurple: 28,
    reloadSec: 2.4,
    recoil: "low",
    rangeOptimal: "mid",
    notes: "4-round bursts ramp up RPM with continuous fire.",
    pro: "Hold trigger across multiple bursts — the ramp-up is the whole point.",
  },
  {
    id: "hemlok",
    name: "Hemlok Burst AR",
    class: "Assault Rifle",
    ammo: "Heavy",
    tier: "B",
    damageBody: 22,
    damageHead: 44,
    rpm: 520,
    magBase: 18,
    magPurple: 30,
    reloadSec: 2.4,
    recoil: "medium",
    rangeOptimal: "mid",
    notes: "3-round burst. Single-fire mode for long range.",
    pro: "Switch to single-fire past 50m — burst grouping breaks too wide.",
  },
  {
    id: "r99",
    name: "R-99 SMG",
    class: "SMG",
    ammo: "Light",
    tier: "S",
    damageBody: 11,
    damageHead: 22,
    rpm: 1080,
    magBase: 20,
    magPurple: 27,
    reloadSec: 1.95,
    recoil: "medium",
    rangeOptimal: "close",
    notes: "Highest fire rate. Melts in close. Empty mag in <1.5s.",
    pro: "Hipfire under 8m beats ADS — laser stagger is free movement.",
  },
  {
    id: "volt",
    name: "Volt SMG",
    class: "SMG",
    ammo: "Energy",
    tier: "S",
    damageBody: 17,
    damageHead: 34,
    rpm: 720,
    magBase: 19,
    magPurple: 26,
    reloadSec: 2.05,
    recoil: "low",
    rangeOptimal: "close-mid",
    notes: "Hitscan-style precision. Top SMG by win rate.",
    pro: "Pair with R-301 — both light ammo, identical fall-off, easy ammo sharing.",
  },
  {
    id: "alternator",
    name: "Alternator SMG",
    class: "SMG",
    ammo: "Light",
    tier: "S",
    damageBody: 17,
    damageHead: 34,
    rpm: 600,
    magBase: 19,
    magPurple: 27,
    reloadSec: 1.9,
    recoil: "low",
    rangeOptimal: "close-mid",
    notes: "Buffed S29: bigger mag + Disruptor hop-up. Highest base damage SMG.",
    pro: "Disruptor rounds shred shields — open every fight with this.",
    isHopUp: "Disruptor Rounds",
  },
  {
    id: "prowler",
    name: "Prowler Burst PDW",
    class: "SMG",
    ammo: "Heavy",
    tier: "A",
    damageBody: 14,
    damageHead: 28,
    rpm: 1267,
    magBase: 20,
    magPurple: 35,
    reloadSec: 2.0,
    recoil: "medium",
    rangeOptimal: "close-mid",
    notes: "5-round bursts. Selectfire hop-up enables full auto.",
    pro: "Selectfire + Prowler is the best mid-range fighter in the game.",
    isHopUp: "Selectfire Receiver",
  },
  {
    id: "car",
    name: "C.A.R. SMG",
    class: "SMG",
    ammo: "Light/Heavy",
    tier: "A",
    damageBody: 13,
    damageHead: 26,
    rpm: 930,
    magBase: 20,
    magPurple: 27,
    reloadSec: 1.85,
    recoil: "medium",
    rangeOptimal: "close-mid",
    notes: "Dual-ammo — feeds from light OR heavy stacks.",
    pro: "Great backup — never run dry, always have ammo for it.",
  },
  {
    id: "spitfire",
    name: "M600 Spitfire",
    class: "LMG",
    ammo: "Light",
    tier: "A",
    damageBody: 19,
    damageHead: 38,
    rpm: 540,
    magBase: 35,
    magPurple: 55,
    reloadSec: 2.85,
    recoil: "low",
    rangeOptimal: "mid",
    notes: "55-round mag with purple — suppression king.",
    pro: "Beam down corridors — recoil pattern is nearly vertical, pull straight down.",
  },
  {
    id: "rampage",
    name: "Rampage LMG",
    class: "LMG",
    ammo: "Heavy",
    tier: "B",
    damageBody: 28,
    damageHead: 56,
    rpm: 300,
    magBase: 28,
    magPurple: 40,
    reloadSec: 3.4,
    recoil: "low",
    rangeOptimal: "mid-long",
    notes: "Use a thermite to amp fire rate by 60% for 30 seconds.",
    pro: "Amp before peeking — slow base RPM hurts otherwise.",
  },
  {
    id: "devotion",
    name: "Devotion LMG",
    class: "LMG",
    ammo: "Energy",
    tier: "A",
    damageBody: 16,
    damageHead: 32,
    rpm: 900,
    magBase: 36,
    magPurple: 54,
    reloadSec: 2.95,
    recoil: "medium",
    rangeOptimal: "mid",
    notes: "Spins up to insane RPM. Turbocharger removes wind-up.",
    pro: "Strafe-shoot — recoil pattern is forgiving with movement.",
    isHopUp: "Turbocharger",
  },
  {
    id: "kraber",
    name: "Kraber .50-Cal",
    class: "Sniper",
    ammo: "Sniper",
    tier: "S",
    damageBody: 145,
    damageHead: 435,
    rpm: 26,
    magBase: 4,
    magPurple: 6,
    reloadSec: 3.8,
    recoil: "high",
    rangeOptimal: "long",
    notes: "Care package only. One-shot headshot up to purple armor.",
    pro: "Quick-swap to a secondary after every shot — slow rechamber gets you killed.",
    isCarePackage: true,
  },
  {
    id: "longbow",
    name: "Longbow DMR",
    class: "Sniper",
    ammo: "Sniper",
    tier: "A",
    damageBody: 55,
    damageHead: 110,
    rpm: 96,
    magBase: 6,
    magPurple: 12,
    reloadSec: 2.6,
    recoil: "low",
    rangeOptimal: "long",
    notes: "Semi-auto sniper. Deadeye's tempo hop-up rewards rhythm shots.",
    pro: "Don't snipe past 200m — bullet drop is real. Use the leading dot.",
  },
  {
    id: "sentinel",
    name: "Sentinel",
    class: "Sniper",
    ammo: "Sniper",
    tier: "B",
    damageBody: 70,
    damageHead: 140,
    rpm: 36,
    magBase: 4,
    magPurple: 6,
    reloadSec: 2.7,
    recoil: "medium",
    rangeOptimal: "long",
    notes: "Bolt action. Amp it with 2 shield cells for +18 damage temporarily.",
    pro: "Amp before the fight, not during — costs 2 cells you'd rather use to heal.",
  },
  {
    id: "chargerifle",
    name: "Charge Rifle",
    class: "Sniper",
    ammo: "Sniper",
    tier: "B",
    damageBody: 90,
    damageHead: 180,
    rpm: 26,
    magBase: 6,
    magPurple: 12,
    reloadSec: 3.6,
    recoil: "low",
    rangeOptimal: "long",
    notes: "Hitscan beam at any range. Long charge before fire.",
    pro: "Use to harass from 300m+ — most teams retreat before you finish the charge.",
  },
  {
    id: "g7scout",
    name: "G7 Scout",
    class: "Marksman",
    ammo: "Light",
    tier: "A",
    damageBody: 36,
    damageHead: 72,
    rpm: 240,
    magBase: 10,
    magPurple: 18,
    reloadSec: 2.4,
    recoil: "low",
    rangeOptimal: "mid-long",
    notes: "Double-tap hop-up sends 2 rounds with 1 trigger pull.",
    pro: "Best mid-range marksman — pair with R-99 for close/long flex.",
    isHopUp: "Double Tap Trigger",
  },
  {
    id: "30-30",
    name: "30-30 Repeater",
    class: "Marksman",
    ammo: "Heavy",
    tier: "B",
    damageBody: 42,
    damageHead: 84,
    rpm: 138,
    magBase: 6,
    magPurple: 12,
    reloadSec: 1.0,
    recoil: "low",
    rangeOptimal: "mid-long",
    notes: "Lever action. Charged shots deal more damage.",
    pro: "Always release fully charged — uncharged shots barely tickle armor.",
  },
  {
    id: "bocek",
    name: "Bocek Compound Bow",
    class: "Marksman",
    ammo: "Arrow",
    tier: "B",
    damageBody: 70,
    damageHead: 140,
    rpm: 84,
    magBase: 1,
    magPurple: 1,
    reloadSec: 0.0,
    recoil: "low",
    rangeOptimal: "mid",
    notes: "Silent. Pick arrows back up. Shatter Caps for shotgun spread.",
    pro: "Shatter Caps hop-up turns it into a silenced shotgun — broken in pubs.",
    isHopUp: "Shatter Caps",
  },
  {
    id: "peacekeeper",
    name: "Peacekeeper",
    class: "Shotgun",
    ammo: "Shotgun",
    tier: "S",
    damageBody: 110,
    damageHead: 165,
    rpm: 78,
    magBase: 5,
    magPurple: 8,
    reloadSec: 2.4,
    recoil: "medium",
    rangeOptimal: "close",
    notes: "Highest one-shot damage. Choke hop-up tightens pellets.",
    pro: "Hold the choke before peeking, release on target — 110+ guaranteed if all pellets land.",
    isHopUp: "Precision Choke",
  },
  {
    id: "mastiff",
    name: "Mastiff",
    class: "Shotgun",
    ammo: "Shotgun",
    tier: "A",
    damageBody: 88,
    damageHead: 144,
    rpm: 102,
    magBase: 4,
    magPurple: 7,
    reloadSec: 1.0,
    recoil: "medium",
    rangeOptimal: "close",
    notes: "Horizontal pellet spread. Reload-per-shell.",
    pro: "Slide-cancel between shots — keeps mobility while reloading.",
  },
  {
    id: "eva8",
    name: "EVA-8 Auto",
    class: "Shotgun",
    ammo: "Shotgun",
    tier: "A",
    damageBody: 63,
    damageHead: 85,
    rpm: 126,
    magBase: 8,
    magPurple: 12,
    reloadSec: 2.4,
    recoil: "low",
    rangeOptimal: "close",
    notes: "Full-auto shotgun. Lower per-shot but high sustain.",
    pro: "Crouch-strafe in shotgun fights — reduces hitbox while spamming pellets.",
  },
  {
    id: "mozambique",
    name: "Mozambique",
    class: "Shotgun",
    ammo: "Shotgun",
    tier: "C",
    damageBody: 45,
    damageHead: 67,
    rpm: 156,
    magBase: 3,
    magPurple: 3,
    reloadSec: 1.4,
    recoil: "low",
    rangeOptimal: "close",
    notes: "Triple-barrel pistol. Hammerpoint hop-up shreds unshielded enemies.",
    pro: "Finisher only — never fight with it past white shield phase.",
    isHopUp: "Hammerpoint Rounds",
  },
  {
    id: "wingman",
    name: "Wingman",
    class: "Pistol",
    ammo: "Sniper",
    tier: "A",
    damageBody: 45,
    damageHead: 90,
    rpm: 156,
    magBase: 6,
    magPurple: 9,
    reloadSec: 2.1,
    recoil: "high",
    rangeOptimal: "mid",
    notes: "Hand cannon. Sniper ammo. Skill-shot precision required.",
    pro: "Don't pre-fire — Wingman rewards holding angles, not pushing.",
  },
  {
    id: "p2020",
    name: "P2020",
    class: "Pistol",
    ammo: "Light",
    tier: "C",
    damageBody: 18,
    damageHead: 27,
    rpm: 420,
    magBase: 10,
    magPurple: 17,
    reloadSec: 1.25,
    recoil: "low",
    rangeOptimal: "close",
    notes: "Floor loot pistol. Hammerpoints shred unshielded.",
    pro: "Hot-drop emergency — drop it the second you find anything else.",
    isHopUp: "Hammerpoint Rounds",
  },
  {
    id: "re45",
    name: "RE-45",
    class: "Pistol",
    ammo: "Light",
    tier: "B",
    damageBody: 12,
    damageHead: 24,
    rpm: 600,
    magBase: 16,
    magPurple: 25,
    reloadSec: 1.5,
    recoil: "low",
    rangeOptimal: "close",
    notes: "Full-auto pistol. Disruptor rounds amp shield damage.",
    pro: "Hot-drop weapon — usable until you find a real SMG.",
    isHopUp: "Disruptor Rounds",
  },
];

// Pre-compute TTK so the UI can sort by it.
export const WEAPONS_WITH_TTK = WEAPONS.map((w) => ({
  ...w,
  ttkMs: ttk(w.damageBody, w.rpm),
  dps: Math.round((w.damageBody * w.rpm) / 60),
}));

export type WeaponWithTTK = (typeof WEAPONS_WITH_TTK)[number];

export const HOP_UPS: { id: string; name: string; tier: "rare" | "epic"; weapons: string[]; text: string }[] = [
  { id: "turbo", name: "Turbocharger", tier: "epic", weapons: ["havoc", "devotion"], text: "Removes wind-up on energy weapons." },
  { id: "selectfire", name: "Selectfire Receiver", tier: "epic", weapons: ["prowler"], text: "Adds full-auto mode to burst weapons." },
  { id: "doubletap", name: "Double Tap Trigger", tier: "rare", weapons: ["g7scout"], text: "Fires 2 rounds in rapid succession." },
  { id: "shattercaps", name: "Shatter Caps", tier: "rare", weapons: ["bocek"], text: "Bow fires shotgun-style spread." },
  { id: "choke", name: "Precision Choke", tier: "rare", weapons: ["peacekeeper"], text: "Tightens shotgun pellet spread when ADS." },
  { id: "hammer", name: "Hammerpoint Rounds", tier: "rare", weapons: ["mozambique", "p2020", "re45"], text: "+34% damage to unshielded enemies." },
  { id: "disruptor", name: "Disruptor Rounds", tier: "epic", weapons: ["alternator", "re45"], text: "+25% damage to shields." },
  { id: "deadeye", name: "Deadeye's Tempo", tier: "rare", weapons: ["sentinel", "longbow"], text: "Fire faster when rhythm-tapping shots." },
];

export function findWeapon(id: string) {
  return WEAPONS_WITH_TTK.find((w) => w.id === id);
}
